//declare a name space object for the application to hold application specific variables and functions
var pip_ns = {};

var pipContext = null;
var url_root = "",url_app="";
pip_ns.host = $(location).attr("host");

if ($(location).attr("hostname") == "localhost")
{
	pip_ns.url_root = "proxy/sap/opu/odata/sap/";
	pip_ns.url_app = location.protocol + "//"+ pip_ns.host + "/myPath_PerformImpPlan/";
}
else
{
	pip_ns.url_root = location.protocol + "//" + pip_ns.host + "/sap/opu/odata/sap/";
	pip_ns.url_app = location.protocol + "//"+ pip_ns.host + "/sap/bc/ui5_ui5/sap/ZPerformImpPlan/";
}	

reviewer_pip_modeldata = [
                          
	                     { 
	                     	substatus :"F",	//PIP Set Objective (Reviewer)
	                     	status:"2",
	                    	obj_action_visible : true,
	                    	obj_action_editable : true,
	                    	action_emp_comments_visible:false,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:false,
	                    	evaluation_perform_dev_visible : false,
	                    	evaluation_achieved_visible : false,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:false,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: false,
	                    	reviewer_ind_visible:false,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:true,
	                    	obj_backToRev_signoffToRev_flag:false,//ZSENDREV_SIGNOF: "Send to Reviewer for signoff" //ZRETURN_REV: "Return to Reviewer for Updates"
	                    	obj_save_sendToEmp_flag : false,	//Save - Send to Employee                    	
	                    	obj_save_signoff_emp_flag : false, // Save and signoff ???
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                    	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:false,
	                    	
	                    	obj_cancel_next_btn_flag:true,	                    	
	                    	action_cancel_next_btn_flag:false,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : true,
	                    	
	                     },
	                     { 
		                     	substatus :"G",	//PIP  Objective Review (HR)
		                     	status:"2",
		                     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:false,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:false,
		                    	evaluation_perform_dev_visible : false,
		                    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:false,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:false,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:false,
		                    	
		                      	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:false,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"H",	//PIP  Objective Signoff (Reviewer)
		                     	status:"2",
		                     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:false,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:false,
		                    	evaluation_perform_dev_visible : false,
		                    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:false,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:false,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : true,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:true,
		                    	
		                      	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"I",	//PIP Objective Signoff (Employee)
		                     	status:"2",
		                     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:true,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:false,
		                    	evaluation_perform_dev_visible : false,
		                    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:false,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:false,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:true,
		                    	
		                      	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"J",	//PIP Objective Setting (Complete)
		                     	status:"2",
		                     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:true,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:false,
		                    	evaluation_perform_dev_visible : false,
		                    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:false,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:false,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:true,
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"Z",	//PIP Assessment (Reviewer)
		                     	status:"4",
		                     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:true,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:true,
		                    	progress_evaluation_visible:true,
		                    	evaluation_perform_dev_visible : true,
		                    	evaluation_achieved_visible : true,
		                    	evaluation_achieved_editable : true,
		                    	progress_emp_comments_visible:false,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:true,
		                    	reviewer_ind_editable:true,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : true,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:true,
		                    	evaluation_tab_visible_flag:true,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:true,
		                    	evaluation_cancel_next_btn_flag:true,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"Y",	//PIP  Assessment Review (Employee)
		                     	status:"4",
		                     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:true,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:true,
		                    	evaluation_perform_dev_visible : true,
		                    	evaluation_achieved_visible : true,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:true,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:true,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:true,
		                    	evaluation_tab_visible_flag:true,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:true,
		                    	evaluation_cancel_next_btn_flag:true,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"4",	//PIP Signoff (HR)
		                     	status:"4",
		                     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:true,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:true,
		                    	evaluation_perform_dev_visible : true,
		                    	evaluation_achieved_visible : true,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:true,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:true,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:true,
		                    	evaluation_tab_visible_flag:true,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:true,
		                    	evaluation_cancel_next_btn_flag:true,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"F",	//PIP Complete
		                     	status:"5",
		                    	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:true,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:true,
		                    	evaluation_perform_dev_visible : true,
		                    	evaluation_achieved_visible : true,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:true,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:true,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:true,
		                    	evaluation_tab_visible_flag:true,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:true,
		                    	evaluation_cancel_next_btn_flag:true,
		                    	
		                    	attachment_icon_visible : true,
		                  },
		                  { 
		                     	substatus :"",	//In Preparation
		                     	status:"1",
		                     	obj_action_visible : true,
		                    	obj_action_editable : true,
		                    	action_emp_comments_visible:false,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:false,
		                    	evaluation_perform_dev_visible : false,
		                    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:false,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: false,
		                    	reviewer_ind_visible:false,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:true,
		                    	obj_backToRev_signoffToRev_flag:false,//ZSENDREV_SIGNOF: "Send to Reviewer for signoff" //ZRETURN_REV: "Return to Reviewer for Updates"
		                    	obj_save_sendToEmp_flag : false,	//Save - Send to Employee                    	
		                    	obj_save_signoff_emp_flag : false, // Save and signoff ???
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:false,
		                    	action_plan_tab_visible_flag:false,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:false,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:false,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : false,
		                  },
	                    
	                 
           ];	

 hr_pip_modeldata = [
                     
                     { 
                     	substatus :"F",	//PIP Set Objective (Reviewer)
                     	status:"2",
                    	obj_action_visible : true,
                    	obj_action_editable : false,
                    	action_emp_comments_visible:false,
                    	action_emp_comments_editable:false,
                    	progress_evaluation_editable:false,
                    	progress_evaluation_visible:false,
                    	evaluation_perform_dev_visible : false,
                    	evaluation_achieved_visible : false,
                    	evaluation_achieved_editable : false,
                    	progress_emp_comments_visible:false,
                    	progress_emp_comments_editable:false,
                    	hr_comments_editable: false,
                    	hr_comments_visible: true,
                    	reviewer_ind_visible:false,
                    	reviewer_ind_editable:false,
                    	
                    	obj_save_sendToHr_btn_flag:false,
                    	obj_backToRev_signoffToRev_flag:false,//ZSENDREV_SIGNOF: "Send to Reviewer for signoff" //ZRETURN_REV: "Return to Reviewer for Updates"
                    	obj_save_sendToEmp_flag : false,	//Save - Send to Employee                    	
                    	obj_save_signoff_emp_flag : false, // Save and signoff ???
                    	assessment_sendToHR_sendToEmp_flag : false,
                    	assessment_save_sendToReviewer_flag : false,
                    	assessment_sendToReviewer_complete_flag:false,
                    	
                    	obj_tab_visible_flag:true,
                    	action_plan_tab_visible_flag:true,
                    	progress_tab_visible_flag:false,
                    	evaluation_tab_visible_flag:false,
                    	final_tab_visible_flag:true,
                    	
                    	obj_cancel_next_btn_flag:true,
                    	action_cancel_next_btn_flag:true,
                    	progress_cancel_next_btn_flag:false,
                    	evaluation_cancel_next_btn_flag:false,
                    	
                    	attachment_icon_visible : true,
                    	
                     },
                     { 
	                     	substatus :"G",	//PIP  Objective Review (HR)
	                     	status:"2",
	                     	obj_action_visible : true,
	                    	obj_action_editable : true,
	                    	action_emp_comments_visible:false,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:false,
	                    	evaluation_perform_dev_visible : false,
	                    	evaluation_achieved_visible : false,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:false,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: true,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:false,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:true,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                    	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"H",	//PIP  Objective Signoff (Reviewer)
	                     	status:"2",
	                     	obj_action_visible : true,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:false,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:false,
	                    	evaluation_perform_dev_visible : false,
	                    	evaluation_achieved_visible : false,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:false,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:false,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                    	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"I",	//PIP Objective Signoff (Employee)
	                     	status:"2",
	                     	obj_action_visible : true,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:true,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:false,
	                    	evaluation_perform_dev_visible : false,
	                    	evaluation_achieved_visible : false,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:false,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:false,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                     	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"J",	//PIP Objective Setting (Complete)
	                     	status:"2",
	                     	obj_action_visible : true,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:true,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:false,
	                    	evaluation_perform_dev_visible : false,
	                    	evaluation_achieved_visible : false,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:false,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:false,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                     	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"Z",	//PIP Assessment (Reviewer)
	                     	status:"4",
	                     	obj_action_visible : true,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:true,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:true,
	                    	evaluation_perform_dev_visible : true,
	                    	evaluation_achieved_visible : true,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:false,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:true,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                     	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"Y",	//PIP  Assessment Review (Employee)
	                     	status:"4",
	                     	obj_action_visible : true,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:true,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:true,
	                    	evaluation_perform_dev_visible : true,
	                    	evaluation_achieved_visible : true,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:true,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:true,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                     	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"4",	//PIP Signoff (HR)
	                     	status:"4",
	                     	obj_action_visible : true,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:true,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:true,
	                    	evaluation_perform_dev_visible : true,
	                    	evaluation_achieved_visible : true,
	                    	evaluation_achieved_editable : true,
	                    	progress_emp_comments_visible:true,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: true,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:true,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:true,
	                    	
	                     	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:true,
	                    	evaluation_tab_visible_flag:true,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:true,
	                    	evaluation_cancel_next_btn_flag:true,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"F",	//PIP Complete
	                     	status:"5",
	                    	obj_action_visible : true,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:true,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:true,
	                    	evaluation_perform_dev_visible : true,
	                    	evaluation_achieved_visible : true,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:true,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: true,
	                    	reviewer_ind_visible:true,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                    	obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:true,
	                    	progress_tab_visible_flag:true,
	                    	evaluation_tab_visible_flag:true,
	                    	final_tab_visible_flag:true,
	                    	
	                    	obj_cancel_next_btn_flag:true,
	                    	action_cancel_next_btn_flag:true,
	                    	progress_cancel_next_btn_flag:true,
	                    	evaluation_cancel_next_btn_flag:true,
	                    	
	                    	attachment_icon_visible : true,
	                  },
	                  { 
	                     	substatus :"",	//In Preparation
	                     	status:"1",
	                     	obj_action_visible : false,
	                    	obj_action_editable : false,
	                    	action_emp_comments_visible:false,
	                    	action_emp_comments_editable:false,
	                    	progress_evaluation_editable:false,
	                    	progress_evaluation_visible:false,
	                    	evaluation_perform_dev_visible : false,
	                    	evaluation_achieved_visible : false,
	                    	evaluation_achieved_editable : false,
	                    	progress_emp_comments_visible:false,
	                    	progress_emp_comments_editable:false,
	                    	hr_comments_editable: false,
	                    	hr_comments_visible: false,
	                    	reviewer_ind_visible:false,
	                    	reviewer_ind_editable:false,
	                    	
	                    	obj_save_sendToHr_btn_flag:false,
	                    	obj_backToRev_signoffToRev_flag:false,
	                    	obj_save_sendToEmp_flag : false,	                 	
	                    	obj_save_signoff_emp_flag : false, 
	                    	assessment_sendToHR_sendToEmp_flag : false,
	                    	assessment_save_sendToReviewer_flag : false,
	                    	assessment_sendToReviewer_complete_flag:false,
	                    	
	                    	obj_tab_visible_flag:false,
	                    	action_plan_tab_visible_flag:false,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:false,
	                    	
	                    	obj_cancel_next_btn_flag:false,
	                    	action_cancel_next_btn_flag:false,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : false,
	                  },
                    
                 
       ];

emp_pip_modeldata = [
						{ 
						 	substatus :"F",	//PIP Set Objective (Reviewer)
						 	status:"2",
							obj_action_visible : false,
							obj_action_editable : false,
							action_emp_comments_visible:false,
							action_emp_comments_editable:false,
							progress_evaluation_editable:false,
							progress_evaluation_visible:false,
							evaluation_perform_dev_visible : false,
							evaluation_achieved_visible : false,
	                    	evaluation_achieved_editable : false,
							progress_emp_comments_visible:false,
							progress_emp_comments_editable:false,
							hr_comments_editable: false,
							hr_comments_visible: false,
							reviewer_ind_visible:false,
							reviewer_ind_editable:false,
							
							obj_save_sendToHr_btn_flag:false,
							obj_backToRev_signoffToRev_flag:false,//ZSENDREV_SIGNOF: "Send to Reviewer for signoff" //ZRETURN_REV: "Return to Reviewer for Updates"
							obj_save_sendToEmp_flag : false,	//Save - Send to Employee                    	
							obj_save_signoff_emp_flag : false, // Save and signoff ???
							assessment_sendToHR_sendToEmp_flag : false,
							assessment_save_sendToReviewer_flag : false,
							assessment_sendToReviewer_complete_flag:false,
							
							obj_tab_visible_flag:true,
	                    	action_plan_tab_visible_flag:false,
	                    	progress_tab_visible_flag:false,
	                    	evaluation_tab_visible_flag:false,
	                    	final_tab_visible_flag:false,
	                    	
	                    	obj_cancel_next_btn_flag:false,
	                    	action_cancel_next_btn_flag:false,
	                    	progress_cancel_next_btn_flag:false,
	                    	evaluation_cancel_next_btn_flag:false,
	                    	
	                    	attachment_icon_visible : false,
						 },
						 { 
						     	substatus :"G",	//PIP  Objective Review (HR)
						     	status:"2",
						     	obj_action_visible : false,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:false,
						    	action_emp_comments_editable:false,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:false,
						    	evaluation_perform_dev_visible : false,
						    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:false,
						    	progress_emp_comments_editable:false,
						    	hr_comments_editable: false,
						    	hr_comments_visible: false,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : false, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : false,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:false,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:false,
		                    	
		                    	obj_cancel_next_btn_flag:false,
		                    	action_cancel_next_btn_flag:false,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : false,
						  },
						  { 
						     	substatus :"H",	//PIP  Objective Signoff (Reviewer)
						     	status:"2",
						     	obj_action_visible : false,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:false,
						    	action_emp_comments_editable:false,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:false,
						    	evaluation_perform_dev_visible : false,
						    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:false,
						    	progress_emp_comments_editable:false,
						    	hr_comments_editable: false,
						    	hr_comments_visible: false,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : false, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : false,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:false,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:false,
		                    	
		                    	obj_cancel_next_btn_flag:false,
		                    	action_cancel_next_btn_flag:false,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : false,
						  },
						  { 
						     	substatus :"I",	//PIP Objective Signoff (Employee)
						     	status:"2",
						     	obj_action_visible : true,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:true,
						    	action_emp_comments_editable:true,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:false,
						    	evaluation_perform_dev_visible : false,
						    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:false,
						    	progress_emp_comments_editable:false,
						    	hr_comments_editable: false,
						    	hr_comments_visible: true,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : true, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : false,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : true,
						  },
						  { 
						     	substatus :"J",	//PIP Objective Setting (Complete)
						     	status:"2",
						     	obj_action_visible : true,
		                    	obj_action_editable : false,
		                    	action_emp_comments_visible:true,
		                    	action_emp_comments_editable:false,
		                    	progress_evaluation_editable:false,
		                    	progress_evaluation_visible:false,
		                    	evaluation_perform_dev_visible : false,
		                    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
		                    	progress_emp_comments_visible:false,
		                    	progress_emp_comments_editable:false,
		                    	hr_comments_editable: false,
		                    	hr_comments_visible: true,
		                    	reviewer_ind_visible:false,
		                    	reviewer_ind_editable:false,
		                    	
		                    	obj_save_sendToHr_btn_flag:false,
		                    	obj_backToRev_signoffToRev_flag:false,
		                    	obj_save_sendToEmp_flag : false,	                 	
		                    	obj_save_signoff_emp_flag : false, 
		                    	assessment_sendToHR_sendToEmp_flag : false,
		                    	assessment_save_sendToReviewer_flag : false,
		                    	assessment_sendToReviewer_complete_flag:false,
		                    	
		                    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : true,
						  },
						  { 
						     	substatus :"Z",	//PIP Assessment (Reviewer)
						     	status:"4",
						     	obj_action_visible : true,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:true,
						    	action_emp_comments_editable:false,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:false,
						    	evaluation_perform_dev_visible : false,
						    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:false,
						    	progress_emp_comments_editable:false,
						    	hr_comments_editable: false,
						    	hr_comments_visible: true,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : false, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : false,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : true,
						  },
						  { 
						     	substatus :"Y",	//PIP  Assessment Review (Employee)
						     	status:"4",
						     	obj_action_visible : true,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:true,
						    	action_emp_comments_editable:false,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:true,
						    	evaluation_perform_dev_visible : true,
						    	evaluation_achieved_visible : true,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:true,
						    	progress_emp_comments_editable:true,
						    	hr_comments_editable: false,
						    	hr_comments_visible: true,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : false, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : true,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:true,
		                    	evaluation_tab_visible_flag:true,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:true,
		                    	evaluation_cancel_next_btn_flag:true,
		                    	
		                    	attachment_icon_visible : true,
						  },
						  { 
						     	substatus :"4",	//PIP Signoff (HR)
						     	status:"4",
						     	obj_action_visible : true,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:true,
						    	action_emp_comments_editable:false,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:true,
						    	evaluation_perform_dev_visible : true,
						    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:true,
						    	progress_emp_comments_editable:false,
						    	hr_comments_editable: false,
						    	hr_comments_visible: true,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : false, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : false,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:true,
		                    	evaluation_tab_visible_flag:true,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:true,
		                    	evaluation_cancel_next_btn_flag:true,
		                    	
		                    	attachment_icon_visible : true,
						 
						  },
						  { 
						     	substatus :"F",	//PIP Complete
						     	status:"5",
						    	obj_action_visible : true,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:true,
						    	action_emp_comments_editable:false,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:true,
						    	evaluation_perform_dev_visible : true,
						    	evaluation_achieved_visible : true,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:true,
						    	progress_emp_comments_editable:false,
						    	hr_comments_editable: false,
						    	hr_comments_visible: true,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : false, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : false,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:true,
		                    	action_plan_tab_visible_flag:true,
		                    	progress_tab_visible_flag:true,
		                    	evaluation_tab_visible_flag:true,
		                    	final_tab_visible_flag:true,
		                    	
		                    	obj_cancel_next_btn_flag:true,
		                    	action_cancel_next_btn_flag:true,
		                    	progress_cancel_next_btn_flag:true,
		                    	evaluation_cancel_next_btn_flag:true,
		                    	
		                    	attachment_icon_visible : true,
						  },
						  { 
						     	substatus :"",	//In Preparation
						     	status:"1",
						     	obj_action_visible : false,
						    	obj_action_editable : false,
						    	action_emp_comments_visible:false,
						    	action_emp_comments_editable:false,
						    	progress_evaluation_editable:false,
						    	progress_evaluation_visible:false,
						    	evaluation_perform_dev_visible : false,
						    	evaluation_achieved_visible : false,
		                    	evaluation_achieved_editable : false,
						    	progress_emp_comments_visible:false,
						    	progress_emp_comments_editable:false,
						    	hr_comments_editable: false,
						    	hr_comments_visible: false,
						    	reviewer_ind_visible:false,
						    	reviewer_ind_editable:false,
						    	
						    	obj_save_sendToHr_btn_flag:false,
						    	obj_backToRev_signoffToRev_flag:false,
						    	obj_save_sendToEmp_flag : false,	                 	
						    	obj_save_signoff_emp_flag : false, 
						    	assessment_sendToHR_sendToEmp_flag : false,
						    	assessment_save_sendToReviewer_flag : false,
						    	assessment_sendToReviewer_complete_flag:false,
						    	
						    	obj_tab_visible_flag:false,
		                    	action_plan_tab_visible_flag:false,
		                    	progress_tab_visible_flag:false,
		                    	evaluation_tab_visible_flag:false,
		                    	final_tab_visible_flag:false,
		                    	
		                    	obj_cancel_next_btn_flag:false,
		                    	action_cancel_next_btn_flag:false,
		                    	progress_cancel_next_btn_flag:false,
		                    	evaluation_cancel_next_btn_flag:false,
		                    	
		                    	attachment_icon_visible : false,
						  },
];

/* Function to call service to get column texts */
/*function getPipTemplateService(){
	var readRequestURL = "/ElementsTextSet?$filter=IvAppraisalType eq '"+myPathContext.documentText.PIP+"'";
	myPathContext.dashboard_ODataModel.read(readRequestURL, null, null, false,     
    function(oData,oResponse){
		
		for(var i=0; i<oData.results.length; i++){
			var record = { name: oData.results[i].Name, infotext: oData.results[i].Tline};
			myPathContext.pip_template[oData.results[i].RowIid] = record;
		}
			
		myPathContext.pip_template_loaded = true;
	},
	function(oError){
    	 //TO DO - code to display error message
	});
	
}*/
